version: '3.8'

networks:
  car-repair-network:
    driver: bridge

services:
  app:
    build:
      context: ../
      dockerfile: docker/nodejs/Dockerfile
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - car-repair-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["npm", "run", "start:dev"]

  db:
    container_name: car-repair-postgres
    image: postgres:${POSTGRES_VERSION:-16}
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - car-repair-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - car-repair-network

volumes:
  car-repair-pg-data: