version: '3.8'

networks:
  car-repair-network:
    driver: bridge

services:
  db:
    container_name: car-repair-postgres
    build:
      context: ../../
      dockerfile: backend/docker/db/Dockerfile
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION:-16}
    restart: unless-stopped
    volumes:
      - car-repair-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - car-repair-network

  app:
    container_name: docker-app-1
    build:
      context: ../../
      dockerfile: backend/docker/app/Dockerfile
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - car-repair-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    container_name: docker-nginx-1
    build:
      context: ../../
      dockerfile: backend/docker/nginx/Dockerfile
      args:
        FRONTEND_CONTEXT: frontend
        ADMIN_CONTEXT: admin
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - car-repair-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro

volumes:
  car-repair-pg-data: